// This file contains the complete list of all possible items in the game.
// It is used to render disabled UI for items the player hasn't encountered yet.

export const MASTER_TOOL_LIST = [
    { "Name": "Bone Necklace", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Silk Spear", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Compass", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Mosscreep Tool 1", "Data": { "IsUnlocked": false, "IsHidden": true, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Straight Pin", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 12 } },
    { "Name": "Bell Bind", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Rosary Magnet", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Tri Pin", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 20 } },
    { "Name": "Thread Sphere", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Flea Brew", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 6 } },
    { "Name": "Harpoon", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 17 } },
    { "Name": "Dead Mans Purse", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Extractor", "Data": { "IsUnlocked": false, "IsHidden": true, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Lifeblood Syringe", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 6 } },
    { "Name": "Barbed Wire", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Poison Pouch", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Sting Shard", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 12 } },
    { "Name": "Lava Charm", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Weighted Anklet", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Thief Charm", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Screw Attack", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 13 } },
    { "Name": "Quickbind", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Brolly Spike", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Cogwork Saw", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 16 } },
    { "Name": "Scuttlebrace", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Cogwork Flier", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 8 } },
    { "Name": "Dazzle Bind", "Data": { "IsUnlocked": false, "IsHidden": true, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Parry", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Silk Bomb", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Silk Snare", "Data": { "IsUnlocked": false, "IsHidden": true, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 8 } },
    { "Name": "Sprintmaster", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Wallcling", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Spool Extender", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Flintstone", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 5 } },
    { "Name": "Thief Claw", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Magnetite Dice", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Conch Drill", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 14 } },
    { "Name": "Silk Charge", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Rosary Cannon", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 6 } },
    { "Name": "Pimpilo", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 6 } },
    { "Name": "Maggot Charm", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Wisp Lantern", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "WebShot Architect", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 24 } },
    { "Name": "Revenge Crystal", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Zap Imbuement", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "White Ring", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Flea Charm", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Multibind", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Shakra Ring", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 20 } },
    { "Name": "Tack", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 10 } },
    { "Name": "Musician Charm", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Dazzle Bind Upgraded", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Pinstress Tool", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Silk Boss Needle", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Mosscreep Tool 2", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Curve Claws", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 16 } },
    { "Name": "Fractured Mask", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 1 } },
    { "Name": "Longneedle", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Quick Sling", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Reserve Bind", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 1 } },
    { "Name": "Lightning Rod", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 10 } }
];

export const MASTER_COLLECTABLE_LIST = [
    { "Name": "Mossberry", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rosary_Set_Frayed", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Quill", "Data": { "Amount": 0, "IsSeenMask": 56, "AmountWhileHidden": 0 } },
    { "Name": "Tool Metal", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rosary_Set_Medium", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Pilgrim Rag", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Common Spine", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Dresses", "Data": { "Amount": 0, "IsSeenMask": 10, "AmountWhileHidden": 0 } },
    { "Name": "R Bone Record", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Crest Socket Unlocker", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rosary_Set_Small", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Shell Flower", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Great Shard", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Simple Key", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Plasmium", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Shard Pouch", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Crow Feather", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Tool Pouch&Kit Inv", "Data": { "Amount": 0, "IsSeenMask": 4, "AmountWhileHidden": 0 } },
    { "Name": "Silk Grub", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Snare Soul Swamp Bug", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Silver Bellclapper", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rock Roller Item", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Ward Key", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "R Psalm Cylinder", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Cog Heart Pieces", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Pale_Oil", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Fine Pin", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Slab Key", "Data": { "Amount": 0, "IsSeenMask": 68, "AmountWhileHidden": 0 } },
    { "Name": "R Seal Chit", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Fixer Idol", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "R Weaver Totem", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Enemy Morsel Shredded", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "R Weaver Record", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Materium", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Skull King Fragment", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rosary_Set_Huge_White", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Coral Ingredient", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Broken SilkShot", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Vintage Nectar", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rosary_Set_Large", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Mossberry Stew", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Architect Key", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Enemy Morsel Seared", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Grey Memento", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Beastfly Remains", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Ant Trapper Item", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Wood Witch Item", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Pristine Core", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Pickled Roach Egg", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Roach Corpse Item", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Belltown House Key", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Courier Supplies Gourmand", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Song Pilgrim Cloak", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Courier Supplies Slave", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Snare Soul Bell Hermit", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Extractor Machine Pins", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Courier Supplies Mask Maker", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Snare Soul Churchkeeper", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Dock Key", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "R Ancient Egg", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Farsight", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Coral Heart", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Flower Heart", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Craw Summons", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Hunter Heart", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Crowman Memento", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Crawbell", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Clover Heart", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "White Flower", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Memento Garmond", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Plasmium Blood", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Plasmium Gland", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Memento Surface", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Ward Boss Key", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Enemy Morsel Speared", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Broodmother Remains", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Courier Supplies", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } }
];

export const MASTER_RELIC_LIST = [
    { "Name": "Bone Record Bone_East_14", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Bone Record Greymoor_flooded_corridor", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Psalm Cylinder Grindle", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Seal Chit Ward Corpse", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Psalm Cylinder Hang", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Psalm Cylinder Librarian", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Librarian Melody Cylinder", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Weaver Totem Slab_Bottom", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Weaver Record Weave_08", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Seal Chit Aspid_01", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Bone Record Wisp Top", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Psalm Cylinder Library Roof", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Seal Chit City Merchant", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Weaver Totem Witch", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Ancient Egg Abyss Middle", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Weaver Totem Bonetown_upper_room", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Seal Chit Silk Siphon", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Psalm Cylinder Ward", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Weaver Record Sprint_Challenge", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } }
];

export const MASTER_QUEST_LIST = [
    { "Name": "Citadel Seeker", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Mossberry Collection Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Mossberry Collection 1", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Building Materials", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Pilgrim Rags", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save the Fleas Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save the Fleas", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Brolly Get", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Journal", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Building Materials (Bridge)", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Rock Rollers", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "The Threadspun Town", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Shell Flowers", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Skull King", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Extractor Blue", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Shiny Bell Goomba", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save Courier Short", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Crow Feathers Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "A Pinsmiths Tools", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Crow Feathers", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Huntress Quest", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Belltown House Start", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Grand Gate Bellshrines", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Citadel Investigate", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Citadel Ascent", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Citadel Ascent Melodies", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Great Gourmand", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Songclave Donation 1", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Fine Pins", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save City Merchant", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Building Materials (Statue)", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Belltown House Mid", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Beastfly Hunt", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save Sherma", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Citadel Ascent Lift", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Citadel Ascent Silk Defeat", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Sprintmaster Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Sprintmaster Race", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Ant Trapper", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Mr Mushroom", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save Courier Tall", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Shakra Final Quest", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Roach Killing", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Song Pilgrim Cloaks", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Songclave Donation 2", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Courier Delivery Dustpens Slave", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Soul Snare Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save City Merchant Bridge", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Broodmother Hunt", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Soul Snare", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Wood Witch Curse", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Doctor Curse Cure", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Courier Delivery Mask Maker", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Silk Defeat Snare", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt0", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt1 Shamans", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Bellbeast Rescue", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Diving Bell Pt1 Inspect", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Diving Bell Pt2 Ballow", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Diving Bell Pt3 Descend", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt2 Abyss", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt3 Escape", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt4 Return", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt5 Heart", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Tormented Trobbio", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Pinstress Battle Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Flea Games Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Destroy Thread Cores", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Flea Games", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Pinstress Battle", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt6 Flower", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Garmond Black Threaded", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Extractor Blue Worms", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Huntress Quest Runt", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Song Knight", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Courier Delivery Songclave", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } }
];

export const MASTER_CREST_LIST = [
    { "Name": "Hunter", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Reaper", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Wanderer", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Warrior", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Hunter_v2", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Toolmaster", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Cursed", "Data": { "IsUnlocked": false, "Slots": [], "DisplayNewIndicator": false } },
    { "Name": "Witch", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Spell", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Hunter_v3", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } }
];

export const MASTER_JOURNAL_LIST = [
    { "Name": "MossBone Crawler", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "MossBone Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Roller", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Mossbone Mother", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Goomba", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Goomba Large", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Flyer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Circler", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim 03", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim 01", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Aspid Collector", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim Moss Spitter", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Beast", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Crawler", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim StaffWielder", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Dock Worker", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Dock Flyer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Hopper", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Hunter Buzzer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Hunter Tiny", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Hunter Child", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Shield Dock Worker", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Tar Slug", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Lace", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Fields Flock Flyers", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Fields Goomba", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Hunter Throw", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Fields Flyer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Circler Vicious", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Dock Bomber", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Spine Floater", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim 04", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim 02", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Golem", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim Bell Thrower", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Farmer Catcher", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Crow", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Farmer Centipede", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Mitefly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Farmer Scissors", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Mite", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Gnat Giant", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Crowman", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Crowman Dagger", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pond Skater", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim Fisher", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Shellwood Gnat", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Shellwood Wasp", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Flower Drifter", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Stick Insect Charger", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Stick Insect", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bloom Shooter", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Rosary Pilgrim", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Stick Insect Flyer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Splinter Queen", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bloom Puncher", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bell Goomba", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bell Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim Bellthrower Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Worm", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Roof Crab", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Crypt Worm", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Spinner Boss", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Roachfeeder Short", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Dustroach", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Roachfeeder Tall", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Roachkeeper", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Swamp Mosquito", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Swamp Goomba", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Rosary Thief", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Swamp Muckman", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Slab Fly Large", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Wraith", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bloat Roach", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Swamp Drifter", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Dustroach Pollywog", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Swamp Muckman Tall", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Swamp Shaman", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Swamp Ductsucker", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Swamp Barnacle", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Rock Roller", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Hunter", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Hunter Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Flyer Giant", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Spitter", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Judge", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Blade Spider", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim Hiker", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Conch Shooter", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Conch Driller Giant", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Last Judge", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Understore Thrower", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Understore Poker", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Understore Small", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim 03 Understore", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Mite Heavy", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Understore Heavy", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim Staff Understore", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Citadel Bat", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Pilgrim 01", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Reed", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim 01 Song", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Pilgrim 03", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim 03 Song", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim 04 Song", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Automaton Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim 02 Song", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim Stomper Song", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Reed Grand", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Clockwork Dancer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Threaded Husk", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Creeper", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Understore Mite Giant", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Understore Automaton", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Understore Automaton EX", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Slab Fly Mid", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Slab Fly Small", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Slab Prisoner Leaper New", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Handmaiden", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Pilgrim Maestro", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Administrator", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Heavy Sentry", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Automaton 01", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Automaton Goomba", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Automaton Fly Spike", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Automaton 02", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Automaton Shield", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Automaton Ball", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Scholar", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Scrollkeeper", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Lightbearer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Trobbio", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Blade Spider Hang", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Crystal Drifter", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Weaver Servitor Large", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Peaks Drifter", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Slab Prisoner Fly New", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "First Weaver", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Phantom", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Weaver Servitor", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Thumper", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Goomba Bounce Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Dock Charger", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Dock Guard Thrower", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Tar Slug Huge", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Rhino", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Goomba Large", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Conch Shooter Heavy", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "MossBone Crawler Fat", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Giant Flea", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pilgrim 05", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Skull King", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Hopper Giant", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Spike Goomba", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Conch Stabber", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Conch Driller", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Shell Fossil Mimic", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Vampire Gnat", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Silk Boss", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Swamp Mosquito Skinny", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Farmer Wisp", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Wisp Pyre Effigy", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Wisp", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Crystal Drifter Giant", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Zap Core Enemy", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Warrior Grey", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Hunter Trapper", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Roachkeeper Chef Tiny", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Roachkeeper Chef", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Pilgrim 02", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Citadel Bat Large", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Small Crab", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Giant Centipede", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Abyss Crawler", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Gloomfly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Gloom Beast", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Abyss Crawler Large", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Void Tendrils", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Goombas", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Swimmer Small", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Warrior", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Flyer Throw", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Swimmer Fat", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Flyer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Hunter", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Big Jellyfish", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Brawler", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Spike Swimmer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Bubble Brute", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Poke Swimmer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral King", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Seth", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Flower Queen", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Hunter Chief", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Hunter Queen", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Crowman Dagger Juror", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Crowman Juror", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Crowman Juror Tiny", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Crawfather", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Hornet Dragonfly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Grasshopper Slasher", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Grass Goomba", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Grasshopper Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Dragonfly Large", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Cloverstag", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Cloverstag White", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Grasshopper Child", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Lilypad Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Clover Dancer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Lilypad Trap", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Tormented Trobbio", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Black Thread Core", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Pinstress Boss", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "White Palace Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Garmond", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Lost Lace", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Worm BlueBlood", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Blue Assistant", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Bone Worm BlueTurret", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Centipede Trap", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Spike Lazy Flyer", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Surface Scuttler", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Threaded Husk Spin", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Conductor Boss", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Scholar Acolyte", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Song Knight", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Lifeblood Fly", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Arborium Keeper", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Coral Judge Child", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Slab Fly Small Fresh", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Slab Fly Broodmother", "Record": { "Kills": 0, "HasBeenSeen": false } },
    { "Name": "Maggots", "Record": { "Kills": 0, "HasBeenSeen": false } }
];