// This file contains the complete list of all possible items in the game.
// It is used to render disabled UI for items the player hasn't encountered yet.

export const MASTER_TOOL_LIST = [
    { "Name": "Bone Necklace", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Silk Spear", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Compass", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Mosscreep Tool 1", "Data": { "IsUnlocked": false, "IsHidden": true, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Straight Pin", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 12 } },
    { "Name": "Bell Bind", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Rosary Magnet", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Tri Pin", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 20 } },
    { "Name": "Thread Sphere", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Flea Brew", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 6 } },
    { "Name": "Harpoon", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 17 } },
    { "Name": "Dead Mans Purse", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Extractor", "Data": { "IsUnlocked": false, "IsHidden": true, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Lifeblood Syringe", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 6 } },
    { "Name": "Barbed Wire", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Poison Pouch", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Sting Shard", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 12 } },
    { "Name": "Lava Charm", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Weighted Anklet", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Thief Charm", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Screw Attack", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 13 } },
    { "Name": "Quickbind", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Brolly Spike", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Cogwork Saw", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 16 } },
    { "Name": "Scuttlebrace", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Cogwork Flier", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 8 } },
    { "Name": "Dazzle Bind", "Data": { "IsUnlocked": false, "IsHidden": true, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Parry", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Silk Bomb", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Silk Snare", "Data": { "IsUnlocked": false, "IsHidden": true, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 8 } },
    { "Name": "Sprintmaster", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Wallcling", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Spool Extender", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Flintstone", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 5 } },
    { "Name": "Thief Claw", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Magnetite Dice", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Conch Drill", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 14 } },
    { "Name": "Silk Charge", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Rosary Cannon", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 6 } },
    { "Name": "Pimpilo", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 6 } },
    { "Name": "Maggot Charm", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Wisp Lantern", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "WebShot Architect", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 24 } },
    { "Name": "Revenge Crystal", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Zap Imbuement", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "White Ring", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Flea Charm", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Multibind", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Shakra Ring", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 20 } },
    { "Name": "Tack", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 10 } },
    { "Name": "Musician Charm", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Dazzle Bind Upgraded", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Pinstress Tool", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Silk Boss Needle", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Mosscreep Tool 2", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Curve Claws", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 16 } },
    { "Name": "Fractured Mask", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 1 } },
    { "Name": "Longneedle", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Quick Sling", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 0 } },
    { "Name": "Reserve Bind", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 1 } },
    { "Name": "Lightning Rod", "Data": { "IsUnlocked": false, "IsHidden": false, "HasBeenSeen": false, "HasBeenSelected": false, "AmountLeft": 10 } }
];

export const MASTER_COLLECTABLE_LIST = [
    { "Name": "Mossberry", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rosary_Set_Frayed", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Quill", "Data": { "Amount": 0, "IsSeenMask": 56, "AmountWhileHidden": 0 } },
    { "Name": "Tool Metal", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rosary_Set_Medium", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Pilgrim Rag", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Common Spine", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Dresses", "Data": { "Amount": 0, "IsSeenMask": 10, "AmountWhileHidden": 0 } },
    { "Name": "R Bone Record", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Crest Socket Unlocker", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rosary_Set_Small", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Shell Flower", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Great Shard", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Simple Key", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Plasmium", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Shard Pouch", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Crow Feather", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Tool Pouch&Kit Inv", "Data": { "Amount": 0, "IsSeenMask": 4, "AmountWhileHidden": 0 } },
    { "Name": "Silk Grub", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Snare Soul Swamp Bug", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Silver Bellclapper", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rock Roller Item", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Ward Key", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "R Psalm Cylinder", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Cog Heart Pieces", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Pale_Oil", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Fine Pin", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Slab Key", "Data": { "Amount": 0, "IsSeenMask": 68, "AmountWhileHidden": 0 } },
    { "Name": "R Seal Chit", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Fixer Idol", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "R Weaver Totem", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Enemy Morsel Shredded", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "R Weaver Record", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Materium", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Skull King Fragment", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rosary_Set_Huge_White", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Coral Ingredient", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Broken SilkShot", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Vintage Nectar", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Rosary_Set_Large", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Mossberry Stew", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Architect Key", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Enemy Morsel Seared", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Grey Memento", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Beastfly Remains", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Ant Trapper Item", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Wood Witch Item", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Pristine Core", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Pickled Roach Egg", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Roach Corpse Item", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Belltown House Key", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Courier Supplies Gourmand", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Song Pilgrim Cloak", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Courier Supplies Slave", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Snare Soul Bell Hermit", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Extractor Machine Pins", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Courier Supplies Mask Maker", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Snare Soul Churchkeeper", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Dock Key", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "R Ancient Egg", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Farsight", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Coral Heart", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Flower Heart", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Craw Summons", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Hunter Heart", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Crowman Memento", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Crawbell", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Clover Heart", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "White Flower", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Memento Garmond", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Plasmium Blood", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Plasmium Gland", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Memento Surface", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Ward Boss Key", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Enemy Morsel Speared", "Data": { "Amount": 0, "IsSeenMask": 1, "AmountWhileHidden": 0 } },
    { "Name": "Broodmother Remains", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } },
    { "Name": "Courier Supplies", "Data": { "Amount": 0, "IsSeenMask": 0, "AmountWhileHidden": 0 } }
];

export const MASTER_RELIC_LIST = [
    { "Name": "Bone Record Bone_East_14", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Bone Record Greymoor_flooded_corridor", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Psalm Cylinder Grindle", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Seal Chit Ward Corpse", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Psalm Cylinder Hang", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Psalm Cylinder Librarian", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Librarian Melody Cylinder", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Weaver Totem Slab_Bottom", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Weaver Record Weave_08", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Seal Chit Aspid_01", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Bone Record Wisp Top", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Psalm Cylinder Library Roof", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Seal Chit City Merchant", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Weaver Totem Witch", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Ancient Egg Abyss Middle", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Weaver Totem Bonetown_upper_room", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Seal Chit Silk Siphon", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Psalm Cylinder Ward", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } },
    { "Name": "Weaver Record Sprint_Challenge", "Data": { "IsCollected": false, "IsDeposited": false, "HasSeenInRelicBoard": false } }
];

export const MASTER_QUEST_LIST = [
    { "Name": "Citadel Seeker", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Mossberry Collection Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Mossberry Collection 1", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Building Materials", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Pilgrim Rags", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save the Fleas Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save the Fleas", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Brolly Get", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Journal", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Building Materials (Bridge)", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Rock Rollers", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "The Threadspun Town", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Shell Flowers", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Skull King", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Extractor Blue", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Shiny Bell Goomba", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save Courier Short", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Crow Feathers Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "A Pinsmiths Tools", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Crow Feathers", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Huntress Quest", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Belltown House Start", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Grand Gate Bellshrines", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Citadel Investigate", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Citadel Ascent", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Citadel Ascent Melodies", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Great Gourmand", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Songclave Donation 1", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Fine Pins", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save City Merchant", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Building Materials (Statue)", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Belltown House Mid", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Beastfly Hunt", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save Sherma", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Citadel Ascent Lift", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Citadel Ascent Silk Defeat", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Sprintmaster Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Sprintmaster Race", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Ant Trapper", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Mr Mushroom", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save Courier Tall", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Shakra Final Quest", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Roach Killing", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Song Pilgrim Cloaks", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Songclave Donation 2", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Courier Delivery Dustpens Slave", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Soul Snare Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Save City Merchant Bridge", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Broodmother Hunt", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Soul Snare", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Wood Witch Curse", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Doctor Curse Cure", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Courier Delivery Mask Maker", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Silk Defeat Snare", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt0", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt1 Shamans", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Bellbeast Rescue", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Diving Bell Pt1 Inspect", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Diving Bell Pt2 Ballow", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Diving Bell Pt3 Descend", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt2 Abyss", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt3 Escape", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt4 Return", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt5 Heart", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Tormented Trobbio", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Pinstress Battle Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Flea Games Pre", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Destroy Thread Cores", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Flea Games", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Pinstress Battle", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Black Thread Pt6 Flower", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Garmond Black Threaded", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Extractor Blue Worms", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Huntress Quest Runt", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Song Knight", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } },
    { "Name": "Courier Delivery Songclave", "Data": { "HasBeenSeen": false, "IsAccepted": false, "CompletedCount": 0, "IsCompleted": false, "WasEverCompleted": false } }
];

export const MASTER_CREST_LIST = [
    { "Name": "Hunter", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Reaper", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Wanderer", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Warrior", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Hunter_v2", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Toolmaster", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Cursed", "Data": { "IsUnlocked": false, "Slots": [], "DisplayNewIndicator": false } },
    { "Name": "Witch", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Spell", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } },
    { "Name": "Hunter_v3", "Data": { "IsUnlocked": false, "Slots": [{ "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }, { "IsUnlocked": false }], "DisplayNewIndicator": false } }
];